accounts/urls.py
from django.urls import re_path
from django.contrib.auth.views import LoginView, logout_then_login, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import register_view, register_confirm_view, edit_profile_view, profile_view, remove_friend, add_friend
from django.urls import reverse_lazy
from .forms import CustomPasswordResetForm


urlpatterns = [
    re_path(r"^login/$", LoginView.as_view(extra_context={"section": "dashboard"}), name="login"),
    re_path(r"^register/$", register_view, name="register"),
    re_path(r"^logout/$", logout_then_login, name="logout"),
    re_path(r"^password_change/$",
            PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                       success_url=reverse_lazy("accounts:password_change_done"),
                                       extra_context={"section": "dashboard"}), name="password_change"),
    re_path(r"^password_change/done/$", PasswordChangeDoneView.as_view(extra_context={"section": "dashboard"}), name="password_change_done"),
    re_path(r"^password_reset/$", PasswordResetView.as_view(form_class=CustomPasswordResetForm,
                                                            success_url=reverse_lazy("accounts:password_reset_done"),
                                                            extra_context={"section": "dashboard"}), name="password_reset"),
    re_path(r"^password_reset/done/$", PasswordResetDoneView.as_view(extra_context={"section": "dashboard"}), name="password_reset_done"),
    re_path(r"^reset/(?P<uidb64>\w+)/(?P<token>[\d\w-]+)/$",
            PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete"),
                                             extra_context={"section": "dashboard"}), name="password_reset_confirm"),
    re_path(r"^reset/done/$", PasswordResetCompleteView.as_view(extra_context={"section": "dashboard"}), name="password_reset_complete"),
    re_path(r"^register_confirm/(?P<uidb64>\d+)/(?P<token>[\w\d-]+)/$", register_confirm_view, name="register_confirm"),
    re_path(r"^user/edit/$", edit_profile_view, name="profile_edit"),
    re_path(r"^user/(?P<user_id>\d+)/$", profile_view, name="profile"),
    re_path(r"^remove_friend/(?P<user_id>\d+)/$", remove_friend, name="remove_friend"),
    re_path(r"^add_friend/(?P<user_id>\d+)/$", add_friend, name="add_friend"),
]

boards/urls.py
from django.urls import re_path
from .views import board_list_view, board_detail_view


urlpatterns = [
    re_path(r"^$", board_list_view, name="board_list"),
    re_path(r"^(?P<player>[\w\d]+)/(?P<board_id>[\d-]+)$", board_detail_view, name="board_detail"),
]

bridge/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import dashboard_view, play_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include(("accounts.urls", "accounts"), namespace="accounts")),
    re_path(r"^$", dashboard_view, name="dashboard"),
    re_path(r"^chat/", include(("chat.urls", "chat"), namespace="chat")),
    re_path(r"^play/$", play_view, name="play"),
    re_path(r"boards/", include(("boards.urls", "boards"), namespace="boards"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import re_path
from .views import room

urlpatterns = [
    re_path(r"^(?P<room_name>[\w\d-]+)/$", room, name="room"),
]

bridge/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from accounts.views import search_users
from django.contrib.auth.models import User
from chat.models import Message
from .tasks import play_task


@login_required
def dashboard_view(request):
    notifications = []
    for user in User.objects.all():
        if Message.objects.filter(author=user.username, to=request.user.username, readed=False).exists():
            notifications.append((user, "chatroom-{}-{}".format(min(request.user.pk, user.pk), max(request.user.pk, user.pk))))
    if "search" in request.GET:
        query = request.GET.get("search")
        users = search_users(query)
        return render(request, "search.html", {"section": "dashboard",
                                               "search_result": users,
                                               "notifications": notifications})
    return render(request, "dashboard.html", {"section": "dashboard",
                                              "notifications": notifications})


@login_required
def play_view(request):
    profile = request.user.profile
    user = request.user
    if not request.GET and not profile.play_status:
        profile.play_status = True
        profile.save()
        play_task.delay(user.username)
    return render(request, "play.html", {"section": "play",
                                         "status_play": profile.play_status})

bridge/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="author" content="Jakub Szulgit">
        <meta name="keywords" content="bridge, pygame, django, cards">
        <meta name="viewport" content="width=device-width">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Titillium+Web:wght@900&display=swap" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <div class="container">
            <div class="logo-container">
                <div class="logo">
                    <div id="logo-title">
                        <span id="colored">B</span>ridge
                    </div>
                    <div id="logo-image">
                        <img src="{% static 'images/logo.png' %}" height="100">
                    </div>
                </div>

                <div class="menu">
                    <div class="menu-item {% if section == 'dashboard' %}selected{% endif %}">
                        <a href="/">Strona główna</a>
                    </div>

                    <div class="menu-item {% if section == 'play' %}selected{% endif %}">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'play' %}">Graj!</a>
                        {% endif %}
                    </div>

                    <div class="menu-item {% if section == 'history' %}selected{% endif %}">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'boards:board_list' %}">Historia</a>
                        {% endif %}
                    </div>

                    <div class="menu-item {% if section == 'account' %}selected{% endif %}">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'accounts:profile_edit' %}">Moje konto</a>
                        {% endif %}
                    </div>

                    <div class="menu-item">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'accounts:logout' %}">Wyloguj się</a>
                        {% else %}
                            <a href="{% url 'accounts:login' %}">Zaloguj</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="content-container">
                {% block content %}
                {% endblock %}
            </div>

            <div class="footer">
                <div class="left-footer">
                    <div class="left-footer-item">
                        <p>Jakub Szulgit &copy; 2020</p>
                    </div>

                    <div class="left-footer-item">
                        <p>jakubszulgit@gmail.com</p>
                    </div>
                </div>
                <div class="right-footer">
                    <div class="right-footer-item">
                        <a href="https://github.com/lucek3332"><img src="{% static 'images/github.png' %}" height="60"></a>
                    </div>

                    <div class="right-footer-item">
                        <a href="https://www.codewars.com/users/lucek3332"><img src="{% static 'images/codewars.png' %}" height="70"></a>
                    </div>

                    <div class="right-footer-item">
                        <a href="."><img src="{% static 'images/linkedin.png' %}" height="60"></a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

bridge/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Bridge!{% endblock %}

{% block content %}
    <div class="content-with-sidebar">
        <div class="content-text">
            <div class="header">
                <h1>Bridge</h1>
            </div>

            <div class="text">
                <p>Witaj {{ request.user.first_name }} na stronie!</p>
            </div>

            <div class="header">
                <h1>Powiadomienia</h1>
            </div>

            <div class="notifications">
                {% for notification in notifications %}
                    {% with n=notification|first link=notification|last %}
                        <p>Masz nieprzeczytane wiadomości od <span class="selected"><a href="{% url 'chat:room' link %}">{{ n }}.</a></span></p>
                    {% endwith %}
                {% empty %}
                    <p>Nie masz żadnych powiadomień.</p>
                {% endfor %}
            </div>
        </div>

        {% include 'sidebar.html' %}
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    setInterval(function updateDiv() {
        $(".notifications").load(" .notifications > *");
    }, 2000);
</script>

{% endblock %}

bridge/templates/play.html
{% extends 'base.html' %}

{% block title %}Bridge!{% endblock %}

{% block content %}
    <div class="content-with-sidebar">
        <div class="content-text">
            <div class="header">
                <h1>Bridge</h1>
            </div>

            <div class="text">
                {% if status_play %}
                    <p>Miłej gry w brydża!</p>
                {% else %}
                    <p>Zagraj w brydża!</p>
                {% endif %}
            </div>

            <div class="header">
                <h1>Powiadomienia</h1>
            </div>

            <div class="notifications">
                {% for notification in notifications %}
                    {% with n=notification|first link=notification|last %}
                        <p>Masz nieprzeczytane wiadomości od <span class="selected"><a href="{% url 'chat:room' link %}">{{ n }}.</a></span></p>
                    {% endwith %}
                {% empty %}
                    <p>Nie masz żadnych powiadomień.</p>
                {% endfor %}
            </div>
        </div>

        {% include 'sidebar.html' %}
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    setInterval(function updateDiv() {
        if(window.location.search.indexOf('&refresh=') == -1) {window.location.search += '&refresh=1';}
        $(".notifications").load(" .notifications > *");
        $(".text").load(" .text > *");
    }, 1000);
</script>

{% endblock %}

bridge/templates/search.html
{% extends 'base.html' %}

{% block title %}Bridge!{% endblock %}

{% block content %}
    <div class="content-with-sidebar">
        <div class="content-profile">
            <div class="header">
                <h1>Wyniki wyszukiwania</h1>
            </div>

            <div class="search-users-wrapper">
                {% for user in search_result %}
                    <div class="search-user-wrapper">
                        <a href="{{ user.profile.get_absolute_url }}">
                            {{ user.username }}
                        </a>
                    </div>
                {% empty %}
                    <div class='message-info'>Żaden z użytkowników nie pasuje do wpisanej frazy.</div>
                {% endfor %}
            </div>
        </div>

        {% include 'sidebar.html' %}
    </div>

{% endblock %}

bridge/templates/sidebar.html
<div class="sidebar">
    <br>
    {% if friends %}
        {% for friend in friends %}
            <div class="friend-wrapper">
                <div class="friend-username">
                    <a href="{{ friend.get_absolute_url }}">{{ friend.user.username }}</a>
                </div>

                <div class="friend-{% if friend.is_online %}online{% else %}offline{% endif %}">
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class='message-info'>Nie masz jeszcze żadnych znajomych.</div>
    {% endif %}
    <div class="search-bar">
        <form action="." method="get">
            <input type="text" name="search">
            <input id="search-button" type="submit" value="Szukaj">
        </form>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    setInterval(function updateDiv() {
        $(".sidebar").load(" .sidebar > *");
    }, 20000);
</script>