accounts/urls.py
from django.urls import re_path
from django.contrib.auth.views import LoginView, logout_then_login, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import register_view, register_confirm_view, edit_profile_view, profile_view, remove_friend, add_friend
from django.urls import reverse_lazy
from .forms import CustomPasswordResetForm


urlpatterns = [
    re_path(r"^login/$", LoginView.as_view(extra_context={"section": "dashboard"}), name="login"),
    re_path(r"^register/$", register_view, name="register"),
    re_path(r"^logout/$", logout_then_login, name="logout"),
    re_path(r"^password_change/$",
            PasswordChangeView.as_view(template_name="registration/password_change_form.html",
                                       success_url=reverse_lazy("accounts:password_change_done"),
                                       extra_context={"section": "dashboard"}), name="password_change"),
    re_path(r"^password_change/done/$", PasswordChangeDoneView.as_view(extra_context={"section": "dashboard"}), name="password_change_done"),
    re_path(r"^password_reset/$", PasswordResetView.as_view(form_class=CustomPasswordResetForm,
                                                            success_url=reverse_lazy("accounts:password_reset_done"),
                                                            extra_context={"section": "dashboard"}), name="password_reset"),
    re_path(r"^password_reset/done/$", PasswordResetDoneView.as_view(extra_context={"section": "dashboard"}), name="password_reset_done"),
    re_path(r"^reset/(?P<uidb64>\w+)/(?P<token>[\d\w-]+)/$",
            PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete"),
                                             extra_context={"section": "dashboard"}), name="password_reset_confirm"),
    re_path(r"^reset/done/$", PasswordResetCompleteView.as_view(extra_context={"section": "dashboard"}), name="password_reset_complete"),
    re_path(r"^register_confirm/(?P<uidb64>\d+)/(?P<token>[\w\d-]+)/$", register_confirm_view, name="register_confirm"),
    re_path(r"^user/edit/$", edit_profile_view, name="profile_edit"),
    re_path(r"^user/(?P<user_id>\d+)/$", profile_view, name="profile"),
    re_path(r"^remove_friend/(?P<user_id>\d+)/$", remove_friend, name="remove_friend"),
    re_path(r"^add_friend/(?P<user_id>\d+)/$", add_friend, name="add_friend"),
]

bridge/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import dashboard_view, play_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include(("accounts.urls", "accounts"), namespace="accounts")),
    re_path(r"^$", dashboard_view, name="dashboard"),
    re_path(r"^chat/", include(("chat.urls", "chat"), namespace="chat")),
    re_path(r"^play/$", play_view, name="play"),
    re_path(r"boards/", include(("boards.urls", "boards"), namespace="boards"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import re_path
from .views import room

urlpatterns = [
    re_path(r"^(?P<room_name>[\w\d-]+)/$", room, name="room"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    photo = models.ImageField(upload_to="profiles/", blank=True)
    description = models.TextField(blank=True)
    is_online = models.BooleanField(default=False)
    chat_status = models.IntegerField(default=0)
    play_status = models.BooleanField(default=False)
    friends = models.ManyToManyField("self", symmetrical=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-is_online", "user")

    def get_absolute_url(self):
        return reverse("accounts:profile", args=[str(self.user.pk)])


    def __str__(self):
        return "Profil - {}".format(self.user)

    def __repr__(self):
        return "Profil - {}".format(self.user)

accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import PasswordResetForm
from accounts.tasks import send_mail_task
from django.template import loader
from .models import Profile
from .widgets import CustomClearableFileInput


class UserRegisterForm(ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        help_texts = {
            'username': ""
        }

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("Istnieje już konto z podanym mailem.")
        return email


class ProfileRegisterForm(forms.Form):
    photo = forms.ImageField(required=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Wpisz używane systemy licytacyjne"}), label="Opis", required=False)
    password = forms.CharField(widget=forms.PasswordInput, label="Hasło")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Powtórz hasło")

    def clean_password(self):
        password = self.cleaned_data['password']
        validate_password(password)
        return password

    def clean(self):
        cd = super().clean()
        password = cd.get("password")
        password2 = cd.get("password2")

        if password and password2:
            if password != password2:
                self.add_error("password2", "Hasła nie są identyczne!")


class CustomPasswordResetForm(PasswordResetForm):
    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        send_mail_task.delay(subject, body, from_email, [to_email])


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name"]


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["photo", "description"]
        widgets = {
            "photo": CustomClearableFileInput(),
        }
        labels = {
            "photo": "Zdjęcie",
            "description": "Opis systemu",
        }

accounts/views.py
from django.shortcuts import render
from .forms import ProfileRegisterForm, UserRegisterForm, EditUserForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.signals import user_logged_in, user_logged_out
from .models import Profile
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth import login
from accounts.tasks import send_mail_task
from bridge.settings import EMAIL_HOST_USER
from django.contrib import messages
from django.db.models import Q
from django.dispatch import receiver


def register_view(request):
    if request.method == "POST":
        user_form = UserRegisterForm(request.POST)
        profile_form = ProfileRegisterForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_cd = user_form.cleaned_data
            prof_cd = profile_form.cleaned_data
            new_user = User.objects.create(**user_cd)
            new_user.set_password(prof_cd['password'])
            new_user.is_active = False
            new_user.save()
            profile = Profile.objects.create(user=new_user, photo=prof_cd["photo"], description=prof_cd["description"])
            profile.save()
            token = PasswordResetTokenGenerator().make_token(new_user)
            uid = new_user.pk
            protocol = request.build_absolute_uri().split(":")[0]
            domain = get_current_site(request)
            email_subject = "Aktywacja konta"
            email_message = "Witaj {}! W celu aktywacji konta kliknij poniższy link. " \
                            "{}://{}/accounts/register_confirm/{}/{}".format(new_user.first_name, protocol, domain, uid, token)
            send_mail_task.delay(email_subject, email_message, EMAIL_HOST_USER, [new_user.email])
            return render(request, "registration/register_done.html", {"user": new_user,
                                                                       "profile": profile,
                                                                       "section": "dashboard"})
    else:
        user_form = UserRegisterForm()
        profile_form = ProfileRegisterForm()
    return render(request, "registration/register.html", {"user_form": user_form,
                                                          "profile_form": profile_form,
                                                          "section": "dashboard"})


def register_confirm_view(request, uidb64, token):
    user = get_object_or_404(User, pk=uidb64)
    generator_token = PasswordResetTokenGenerator()
    validtoken = False
    if generator_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        validtoken = True
    return render(request, "registration/register_confirm.html", {"validtoken": validtoken,
                                                                  "section": "dashboard"})


@login_required
def edit_profile_view(request):
    if request.method == "POST":
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(data=request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            messages.info(request, "Zmiany zostały zapisane")
            user_form.save()
            profile_form.save()
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)
    return render(request, "users/edit.html", {"user_form": user_form,
                                               "profile_form": profile_form,
                                               "section": "account"})


@login_required
def profile_view(request, user_id):
    user_profile = get_object_or_404(User, pk=user_id)
    if "search" in request.GET:
        query = request.GET.get("search")
        users = search_users(query)
        return render(request, "search.html", {"section": "dashboard",
                                               "search_result": users})
    return render(request, "users/profile.html", {"user_profile": user_profile,
                                                  "section": "dashboard"})


def search_users(query):
    list_of_queries = query.split(" ")
    search_result = []
    for q in list_of_queries:
        if q != "":
            users = User.objects.filter(Q(username__icontains=q) | Q(first_name__icontains=q) | Q(last_name__icontains=q))
            if users:
                for user in users:
                    search_result.append(user)
    return search_result


@login_required()
def remove_friend(request, user_id):
    user = request.user
    friend = get_object_or_404(User, pk=user_id)
    user.profile.friends.remove(friend.profile)
    return redirect("accounts:profile", user_id=user_id)


@login_required()
def add_friend(request, user_id):
    user = request.user
    friend = get_object_or_404(User, pk=user_id)
    user.profile.friends.add(friend.profile)
    return redirect("accounts:profile", user_id=user_id)


@receiver(user_logged_in)
def get_online(sender, **kwargs):
    user = kwargs["user"]
    profile = get_object_or_404(Profile, user=user)
    profile.is_online = True
    profile.save()


@receiver(user_logged_out)
def get_offline(sender, **kwargs):
    user = kwargs["user"]
    profile = get_object_or_404(Profile, user=user)
    profile.is_online = False
    profile.save()

accounts/templates/users/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Moje konto{% endblock %}

{% block content %}
    <div class="content">
        <div class="header">
            <h1>Moje konto</h1>
        </div>

        <div class="messages">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class='message-{{ message.tags }}' {% endif %}>{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form">
            <div id="profile-image">
                {% if request.user.profile.photo %}
                    <img src="{{ request.user.profile.photo.url }}">
                {% else %}
                    <img src="{% static 'default/no_photo.jpeg' %}">
                {% endif %}
            </div>
            <form action="." method="post" enctype="multipart/form-data">
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                {% csrf_token %}
                <input id="button" type="submit" value="Zapisz">
            </form>
        </div>

        <div class="change-password-link">
            <a href="{% url 'accounts:password_change' %}">
                Zmień hasło
            </a>
        </div>
    </div>
{% endblock %}

accounts/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load chatroom_name %}

{% block title %}Bridge!{% endblock %}

{% block content %}
    <div class="content-with-sidebar">
        <div class="content-profile">
            <div class="header">
                <h1>{{ user_profile.username }}</h1>
            </div>

            <div class="profile-wrapper">
                <div class="profile-image">
                    {% if user_profile.profile.photo %}
                        <img src="{{ user_profile.profile.photo.url }}">
                    {% else %}
                        <img src="{% static 'default/no_photo.jpeg' %}">
                    {% endif %}
                </div>

                <div class="profile-fields">
                    <div class="profile-field">
                        <span id="colored">Imię:</span> {% if user_profile.first_name %}{{ user_profile.first_name }}{% else %}brak danych{% endif %}
                    </div>

                    <div class="profile-field">
                        <span id="colored">Nazwisko:</span> {% if user_profile.last_name %}{{ user_profile.last_name }}{% else %}brak danych{% endif %}
                    </div>

                    <div class="profile-field">
                        <span id="colored">Email:</span> {% if user_profile.email %}{{ user_profile.email }}{% else %}brak danych{% endif %}
                    </div>

                    <div class="profile-field">
                        <span id="colored">Opis systemu:</span> {% if user_profile.profile.description %}{{ user_profile.profile.description }}{% else %}brak danych{% endif %}
                    </div>
                </div>
            </div>
            <div class="profile-buttons">
                <div class="profile-button">
                    <a href="/">
                        <button id="button">Powrót</button>
                    </a>
                </div>

                <div class="profile-button">
                    {% if user_profile.profile in friends %}
                        <a href="{% url 'accounts:remove_friend' user_profile.pk %}">
                            <button id="button">Usuń ze znajomych</button>
                        </a>
                    {% else %}
                        <a href="{% url 'accounts:add_friend' user_profile.pk %}">
                            <button id="button">Dodaj do znajomych</button>
                        </a>
                    {% endif %}
                </div>

                <div class="profile-button">
                    {% with name_chatroom=request|chatroom_name %}
                        <a href="{% if request.user != user_profile %}{% url 'chat:room' name_chatroom %}{% else %}.{% endif %}">
                            <button id="button">Rozmawiaj</button>
                        </a>
                    {% endwith %}
                </div>
            </div>
        </div>

        {% include 'sidebar.html' %}
    </div>
{% endblock %}